### ISSUE TITLE
Crash "java.lang.NoClassDefFoundError: yalter/mousetweaks/api/MouseTweaksIgnore"

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/MixinBooter#1]
1.12.2 mixinbooter-1.0

I was going to try [Thaumic Speedup](https://www.curseforge.com/minecraft/mc-mods/thaumic-speedup), and it lunches fine, throught, i didnt check if it actually speedup anything.
Then i added `mixinbooter`. Game lunches, but when i open inventory `E`, game crashes:
```java
java.lang.NoClassDefFoundError: yalter/mousetweaks/api/MouseTweaksIgnore
	at yalter.mousetweaks.handlers.GuiContainerHandler.isMouseTweaksDisabled(GuiContainerHandler.java:49)
	at yalter.mousetweaks.Main.onUpdateInGui(Main.java:174)
	at yalter.mousetweaks.Main.onUpdateInGame(Main.java:145)
[...]
```

[debug.log](https://www.dropbox.com/s/gdkenexpsv1qvi3/mixin_booter_crush_debug.zip?dl=0)

**Comment by magcicada** [comment]
I have the same issiue[CR1](https://pastebin.ubuntu.com/p/YcnqQWv7Sc/)[CR2](https://pastebin.ubuntu.com/p/FZFNnQ7dVh/)

**Comment by Rongmario** [comment]
> 1.12.2 mixinbooter-1.0
> 
> I was going to try [Thaumic Speedup](https://www.curseforge.com/minecraft/mc-mods/thaumic-speedup), and it lunches fine, throught, i didnt check if it actually speedup anything.
> Then i added `mixinbooter`. Game lunches, but when i open inventory `E`, game crashes:
> 
> ```java
> java.lang.NoClassDefFoundError: yalter/mousetweaks/api/MouseTweaksIgnore
> 	at yalter.mousetweaks.handlers.GuiContainerHandler.isMouseTweaksDisabled(GuiContainerHandler.java:49)
> 	at yalter.mousetweaks.Main.onUpdateInGui(Main.java:174)
> 	at yalter.mousetweaks.Main.onUpdateInGame(Main.java:145)
> [...]
> ```
> 
> [debug.log](https://www.dropbox.com/s/gdkenexpsv1qvi3/mixin_booter_crush_debug.zip?dl=0)

Sorry for the late reply! GitHub either never threw me the issue or I just glanced over it.



> I have the same issiue[CR1](https://pastebin.ubuntu.com/p/YcnqQWv7Sc/)[CR2](https://pastebin.ubuntu.com/p/FZFNnQ7dVh/)

Thank you for the follow up.

This is due to WirelessCraftingTerminals including MouseTweaks API in their mod's jar, it seems outdated and might have some fingerprint issue. To fix, delete this the 'yalter' folder from the jar of WirelessCraftingTerminal.

**Comment by Rongmario** [comment]
If it doesn't work, please follow up and I have another way of fixing it if need.

**Comment by magcicada** [comment]
WirelessCraftingTerminal-1.12.2-3.12.97.jar,WirelessFluidTerminal-1.12.2-1.0.4.jar,WirelessInterfaceTerminal-1.12.2-1.0.2.jar,WirelessPatternTerminal-1.12.2-1.0.3.jar and DankNull-1.12.2-1.7.101.jar of all included 'yalter' folder,I delete all of them and it solved the issue,thanks.

**Comment by Rongmario** [comment]
Thank you. I'll note this on the mod page.

**Comment by magcicada** [comment]
and MouseTweak can't work on them.

**Comment by Rongmario** [comment]
Doesn't load or does MouseTweak functionality not work with their crafting grids?

**Comment by magcicada** [comment]
the MouseTweak doesn't work on all Wireless Terminal.

**Comment by Rongmario** [comment]
Can you try renaming DankNull to something else so its after MouseTweak alphabetically in the `/mods` folder? Do this without deleting any `yalter` folders.

**Comment by magcicada** [comment]
I didn't renaming anything.

**Comment by Rongmario** [comment]
I know, can you try?

**Comment by magcicada** [comment]
ok,I need restart the game,lol,just wait me.

**Comment by magcicada** [comment]
ok,I rename the DankNull and the game doesn't crash,but MouseTweak still can't work on Wireless Terminal and DankNull,I think it’s DankNull’s and Wireless Terminal's problem.

**Comment by magcicada** [comment]
https://github.com/p455w0rd/WirelessCraftingTerminal/issues/121

**Comment by magcicada** [comment]
Thanks a lot.

**Comment by Rongmario** [comment]
Ah I see, thank you for reporting and following up!

**Comment by Krutoy242** [comment]
> Can you try renaming DankNull to something else so its after MouseTweak alphabetically in the `/mods` folder? Do this without deleting any `yalter` folders.

I renamed `DankNull` mod too and it stops crashing on opening inventory.
But, how i could distribute my modpack through CurseForge?
It provides mod list and downloads mods from server with their actual names. MC lunchers cant rename files after DL them.

**Comment by Rongmario** [comment]
You can use [Bansoukou](https://www.curseforge.com/minecraft/mc-mods/bansoko) to patch mod jars at runtime.

**Comment by Krutoy242** [comment]
> You can use [Bansoukou](https://www.curseforge.com/minecraft/mc-mods/bansoko) to patch mod jars at runtime.

What a hack!
Through, i cant see Bansoukou file renaming capabilities. Or you suggest to remove `/yalter` folder in `dankNull.jar`?
