### ISSUE TITLE
Modpack crashed when lauching [MixinBooter 3.2]

### ISSUE THREAD

**Issue by Dark2932** [LoliKingdom/MixinBooter#10]
It caused my modpack crashed.
The old versions can run safely.
crash-report: https://paste.ubuntu.com/p/YZxP7FP9Nj/
latest: https://paste.ubuntu.com/p/6jhR6hS4jf/

**Comment by Macleykun** [comment]
Try this in the meantime https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/3614763

**Comment by Macleykun** [comment]
Include the mixin mod capability

**Comment by Dark2932** [comment]
OK, I have solved.
Thanks!
