### ISSUE TITLE
Mixin doesn't work on client-side with release jar

### ISSUE THREAD

**Issue by Pival81** [LoliKingdom/MixinBooter#18]
I made this small mod that adds compatibility between Botania's Horn of the Wild and Reliquary's Lilypad of Fertility, basically if you use the horn (or the drum of the wild which does the same thing) near the lilypad, the lilypad will break and I didn't like that.
I only needed reliquary's block to implement botania's interface. I also made the itemblock for the lilypad shimmer by overwriting the hasEffect method to return true, just to mess around.
At first everything worked in my dev environment, then nothing worked in release and after a bit of searching I understood I needed mixinbooter, so I implemented it and it works, the lilypad doesn't break when I use the horn.
But for some reason the other mixin isn't working, the itemblock won't shimmer.
Everything does still work in dev.

I even tried to add mixin's debug arguments to my multimc instance, but all it showed was that the mixin loaded fine.

Sorry for the wall of text btw, I've been trying to fix this for the last few days and didn't want to leave anything out.
Here's my mod's repo: https://github.com/Pival81/BotaniaReliquaryCompat

**Comment by Pival81** [comment]
Just now I tried to add another method to the itemblock mixin, just to see if the whole mixin was not working or only part of it.
I injected on the onItemRightClick method and made it display a test string on screen.
This works in both dev and release, so we can be sure that the mixin is being loaded and is partly working, it's just not working on the client.

**Comment by KorewaLidesu** [comment]
Can you uncomment [this](https://github.com/Pival81/BotaniaReliquaryCompat/blob/main/build.gradle#L82) and try again?

**Comment by Pival81** [comment]
> Can you uncomment [this](https://github.com/Pival81/BotaniaReliquaryCompat/blob/main/build.gradle#L82) and try again?

Client still crashes, and it still loads fine from dev running the runClient task. Log [here](https://gist.github.com/Pival81/7162a06643702e9d0375f9a75b1d6d79).


> follow the `build.gradle` over [here](https://github.com/CleanroomMC/TemplateDevEnv/tree/fg5)

I'll try that out tomorrow, thanks. If that doesn't work either, I'll switch to FG 2.3 and see if that helps.

**Comment by Pival81** [comment]
Ok this is weird.
I made my mixin extend the Item class, and had my method override the one from the class I just extended, and now it works in both release and dev environments.

This leads me to think that it's the mixin library itself that's behaving differently, is it perhaps a different version than the one I'm loading from gradle? Or maybe it's configured differently?

**Comment by Pival81** [comment]
I guess this can be closed since it was up to me, even though I don't really know why it works differently between my dev environment and the Mixin library provided by MixinBooter.

**Comment by Rongmario** [comment]
No problem, glad its fixed.
