### ISSUE TITLE
v1.1 Crash on load (ClassNotFoundException: zone.rong.thaumicspeedup.ThaumicSpeedupMixinLoader)

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/MixinBooter#2]
> Should fix all mod loading errors

Actually caused mod loading error 😁
Crash happens even before MC window appear.

Considering crash log, problem comes from **ThaumicSpeedup**, but reverting MixinBooter to version 1.0 solves issue.

[debug.log](https://github.com/LoliKingdom/MixinBooter/files/6466177/debug.log)

**Comment by Rongmario** [comment]
Thanks for reporting, yeah I see the problem :)
