### ISSUE TITLE
Crash on boot, log enclosed?

### ISSUE THREAD

**Issue by adecrepitcabbage** [LoliKingdom/MixinBooter#23]
See title; my modlist works fine, but when I try to add Hesperus *or* loliasm *or* normalasm *or* Performant (which I can't ask for help for because 'performant no longer supports 1.12' because of course it doesn't), they demand MixinBooter.    
No problem, right? But I've tried 7.0, 3.0, 2.0, 3.2-thin, running Mixinboot with Mixin Compatability (the only other issue I could find while searching suggested this; no luck), even MixinBootstrap. All of them with a symbol added if not already added to ensure they get loaded first. When MultiMC crashes, it tells me it suggests a problem with forge. I somewhat doubt that's the cast.

Maybe this can help you help me?

____

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
//// Ed. Note; hugs are nice, but I'd prefer 1000000 years of rest without waking up randomly, thanks...

Time: 2/3/19 1:21 AM
Description: Initializing game

java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class blusunrize.immersiveengineering.common.IEContent
	at blusunrize.immersiveengineering.common.IEContent.registerRecipes(IEContent.java:404)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_124_IEContent_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at blusunrize.immersiveengineering.common.IEContent.registerRecipes(IEContent.java:404)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_124_IEContent_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2875801504 bytes (2742 MB) / 4762107904 bytes (4541 MB) up to 6524764160 bytes (6222 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4000m -Xmx7000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_D1 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                        | Signature                                |
	|:----- |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.5.2768             | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | ambientsounds        | 2.0.0                    | AmbientSounds_v2.3_mc1.12.2.jar               | None                                     |
	| UCH   | apatheticmobs        | 0.1                      | apatheticmobs-0.5.jar                         | None                                     |
	| UCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCH   | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCH   | jei                  | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                      | None                                     |
	| UCH   | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCH   | natura               | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                    | None                                     |
	| UCH   | forestry             | 5.8.0.256                | forestry_1.12.2-5.8.0.256.jar                 | None                                     |
	| UCH   | binniecore           | 2.5.0.144                | binnie-mods-1.12.2-2.5.0.144.jar              | None                                     |
	| UCH   | binniedesign         | 2.5.0.144                | binnie-mods-1.12.2-2.5.0.144.jar              | None                                     |
	| UCH   | genetics             | 2.5.0.144                | binnie-mods-1.12.2-2.5.0.144.jar              | None                                     |
	| UCH   | botany               | 2.5.0.144                | binnie-mods-1.12.2-2.5.0.144.jar              | None                                     |
	| UCH   | extrabees            | 2.5.0.144                | binnie-mods-1.12.2-2.5.0.144.jar              | None                                     |
	| UCH   | extratrees           | 2.5.0.144                | binnie-mods-1.12.2-2.5.0.144.jar              | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2325               | BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| UCH   | bonfires             | 1.1.2                    | Bonfires-1.12-1.1.2.jar                       | None                                     |
	| UCH   | botania              | r1.10-353                | Botania+r1.10-353.jar                         | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCH   | immersiveengineering | 0.12-80                  | ImmersiveEngineering-0.12-80.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | orefarm              | 1.0 - MC 1.12            | Ore+Farm+1.0.jar                              | None                                     |
	| UCH   | peacefulmod          | 1.2.0                    | Peaceful++Mod+[v1.2.0].jar                    | None                                     |
	| UCH   | placebo              | 1.3.2                    | Placebo-1.12.2-1.3.2.jar                      | None                                     |
	| UCH   | plants2              | 2.8.0                    | Plants-1.12.2-2.8.0.jar                       | None                                     |
	| UCH   | shetiphiancore       | 3.5.6                    | shetiphiancore-1.12.0-3.5.6.jar               | None                                     |
	| UCH   | silentlib            | 2.2.18                   | SilentLib-1.12-2.2.18-100.jar                 | None                                     |
	| UCH   | silentgems           | 2.6.9                    | SilentsGems-1.12-2.6.9b-265.jar               | None                                     |
	| UCH   | storagedrawers       | 1.12-5.2.5               | StorageDrawers-1.12.2-5.3.5.jar               | None                                     |
	| UCH   | storagedrawersextra  | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
	| UCH   | terra                | 1.0                      | Terra+1.12.2+-+1.1.4.jar                      | None                                     |
	| UCH   | terraqueous          | 1.4.11                   | terraqueous-1.12.0-1.4.11.jar                 | None                                     |
	| UCH   | thebetweenlands      | 3.3.4                    | TheBetweenlands-3.3.4-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 6700M Series'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6700M Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
	OpenGlRenderer: AMD Radeon HD 6700M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
	
	
____

Below is the crash log proper. 

____

	
	---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// I feel sad now :(

Time: 2022-12-28 00:45:37 PST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1132)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 7514734648 bytes (7166 MB) / 10789322752 bytes (10289 MB) up to 29826220032 bytes (28444 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10000m -Xmx32000m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 86 mods loaded, 86 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version              | Source                                        | Signature                                |
       |:----- |:-------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
       | L     | minecraft            | 1.12.2               | minecraft.jar                                 | None                                     |
       | L     | mcp                  | 9.42                 | minecraft.jar                                 | None                                     |
       | L     | FML                  | 8.0.99.99            | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                | 14.23.5.2860         | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | mixinbooter          | 7.0                  | minecraft.jar                                 | None                                     |
       | L     | foamfixcore          | 7.7.4                | minecraft.jar                                 | None                                     |
       | L     | randompatches        | 1.12.2-1.22.1.10     | randompatches-1.12.2-1.22.1.10.jar            | None                                     |
       | L     | orbis-lib            | 0.2.0                | orbis-lib-1.12.2-0.2.0+build127.jar           | None                                     |
       | L     | aether               | 0.2.6                | aether_ii-1.12.2-0.2.6+build127-universal.jar | None                                     |
       | L     | aiimprovements       | 0.0.1.3              | AIImprovements-1.12-0.0.1b3.jar               | None                                     |
       | L     | aireducer            | 0.3.0                | AIReducer-1.12.2-0.3.0.jar                    | None                                     |
       | L     | akashictome          | 1.2-12               | AkashicTome-1.2-12.jar                        | None                                     |
       | L     | ambientsounds        | 3.0                  | AmbientSounds_v3.0.9_mc1.12.2.jar             | None                                     |
       | L     | apatheticmobs        | 0.1                  | apatheticmobs-0.5.jar                         | None                                     |
       | L     | jei                  | 4.24.2               | HadEnoughItems_1.12.2-4.24.2.jar              | None                                     |
       | L     | quark                | r1.6-177             | Quark-r1.6-177.jar                            | None                                     |
       | L     | autoreglib           | 1.3-32               | AutoRegLib-1.3-32.jar                         | None                                     |
       | L     | baubles              | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
       | L     | bettercaves          | 1.12.2-1.0.3.0       | bettercaves-1.12.2-1.0.3.0.jar                | None                                     |
       | L     | bibliocraft          | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
       | L     | mantle               | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                      | None                                     |
       | L     | natura               | 1.12.2-4.3.2.69      | natura-1.12.2-4.3.2.69.jar                    | None                                     |
       | L     | forestry             | 5.8.2.394            | forestry_1.12.2-5.8.2.394.jar                 | None                                     |
       | L     | binniecore           | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar              | None                                     |
       | L     | binniedesign         | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar              | None                                     |
       | L     | genetics             | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar              | None                                     |
       | L     | botany               | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar              | None                                     |
       | L     | extrabees            | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar              | None                                     |
       | L     | extratrees           | 2.5.1.188            | binnie-mods-1.12.2-2.5.1.188.jar              | None                                     |
       | L     | biometweaker         | 3.2.354              | BiomeTweaker-1.12.2-3.2.354.jar               | None                                     |
       | L     | biomesoplenty        | 7.0.1.2441           | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
       | L     | bonfires             | 1.2.2                | Bonfires-1.12.2-1.2.2-16eac59.jar             | None                                     |
       | L     | thaumcraft           | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
       | L     | botania              | r1.10-361            | Botania+r1.10-361.jar                         | None                                     |
       | L     | cursedlib            | 1.0.0                | FlameLib-1.12.2-0.0.7.jar                     | None                                     |
       | L     | bountifulbaubles     | 0.0.1                | Bountiful+Baubles-1.12.2-0.0.8.jar            | None                                     |
       | L     | ctm                  | MC1.12.2-0.3.3.22    | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
       | L     | chisel               | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
       | L     | cathedral            | 1.12.2-1.9.7k        | Cathedral-1.12.2-1.9.7k.jar                   | None                                     |
       | L     | loliasm              | 5.6                  | censoredasm5.6.jar                            | None                                     |
       | L     | chameleon            | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                      | None                                     |
       | L     | chiselsandbits       | 14.33                | chiselsandbits-14.33.jar                      | None                                     |
       | L     | clumps               | 3.1.2                | Clumps-3.1.2.jar                              | None                                     |
       | L     | earthworks           | 1.3.4.3              | Earthworks-1.12-1.3.6.jar                     | None                                     |
       | L     | familiarfauna        | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
       | L     | fastfurnace          | 1.3.1                | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
       | L     | fastbench            | 1.7.4                | FastWorkbench-1.12.2-1.7.4.jar                | None                                     |
       | L     | foamfix              | @VERSION@            | foamfix-0.10.15-1.12.2.jar                    | None                                     |
       | L     | improvedbackpacks    | 1.12.2-1.4.0.0       | ImprovedBackpacks-1.12.2-1.4.0.0.jar          | None                                     |
       | L     | inventorytweaks      | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar              | None                                     |
       | L     | jeibees              | 0.9.0.5              | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
       | L     | journeymap           | 1.12.2-5.5.5         | journeymap-1.12.2-5.5.5.jar                   | None                                     |
       | L     | jeid                 | 1.0.3-44             | JustEnoughIDs-1.0.3-44.jar                    | None                                     |
       | L     | mystcraft            | 0.13.7.04            | mystcraft-1.12.2-0.13.7.04.jar                | None                                     |
       | L     | gbook                | 2.9.2                | Guidebook-1.12.2-2.9.2.jar                    | None                                     |
       | L     | ltta                 | 1.4.0                | ltta-1.12.2-1.4.0.jar                         | None                                     |
       | L     | lunatriuscore        | 1.2.0.42             | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
       | L     | moremystcraft        | 0.8.4                | moremystcraft-1.12.2-0.8.4.jar                | None                                     |
       | L     | multithreadednoise   | 0.0.2                | MultithreadedNoise-1.12.2-0.0.2.jar           | None                                     |
       | L     | recipehandler        | 0.13                 | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
       | L     | orefarm              | 1.0 - MC 1.12        | Ore+Farm+1.0.jar                              | None                                     |
       | L     | pages                | 1.3.3                | pages-1.12.2-1.3.3.jar                        | None                                     |
       | L     | peaceful             | 1.3.0                | Peaceful++Mod+[v1.5.1].jar                    | None                                     |
       | L     | placebo              | 1.6.0                | Placebo-1.12.2-1.6.0.jar                      | None                                     |
       | L     | plants2              | 2.10.7               | Plants-1.12.2-2.10.7.jar                      | None                                     |
       | L     | rustic               | 1.1.7                | rustic-1.1.7.jar                              | None                                     |
       | L     | silentlib            | 3.0.13               | SilentLib-1.12.2-3.0.13+167.jar               | None                                     |
       | L     | silentgems           | 2.8.18               | SilentsGems-1.12.2-2.8.21+325.jar             | None                                     |
       | L     | stackie              | 1.6.0.48             | Stackie-1.12.2-1.6.0.48-universal.jar         | None                                     |
       | L     | storagedrawers       | 1.12.2-5.4.0         | StorageDrawers-1.12.2-5.4.0.jar               | None                                     |
       | L     | storagedrawersextra  | @VERSION@            | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
       | L     | surge                | 2.0.77               | Surge-1.12.2-2.0.77.jar                       | None                                     |
       | L     | twilightforest       | 3.9.984              | twilightforest-1.12.2-3.9.984-universal.jar   | None                                     |
       | L     | tconstruct           | 1.12.2-2.12.0.157    | TConstruct-1.12.2-2.12.0.157.jar              | None                                     |
       | L     | terra                | 1.0                  | Terra+1.12.2+-+1.1.4.jar                      | None                                     |
       | L     | shetiphiancore       | 3.5.9                | shetiphiancore-1.12.0-3.5.9.jar               | None                                     |
       | L     | terraqueous          | 1.4.17               | terraqueous-1.12.2-1.4.17b.jar                | None                                     |
       | L     | tickdynamic          | 1.0.3                | TickDynamic-1.12.2-1.0.3.jar                  | None                                     |
       | L     | tidychunk            | 1.0.0.0              | TidyChunk-1.12.2-1.0.0.0.jar                  | None                                     |
       | L     | tramplestopper       | 1.2.0.4              | tramplestopper-1.12.2-1.2.0.5-universal.jar   | None                                     |
       | L     | unlimitedchiselworks | 0.2.4                | UnlimitedChiselWorks-0.2.4.jar                | None                                     |
       | L     | unloader             | 1.2.0                | unloader-1.2.0.jar                            | None                                     |
       | L     | phosphor-lighting    | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar   | None                                     |
       | L     | immersiveengineering | 0.12-91              | ImmersiveEngineering-0.12-91.jar              | None                                     |
       | L     | rtg                  | 6.1.0.0-snapshot.1   | RTG-1.12.2-6.1.0.0-snapshot.1.jar             | None                                     |
       | L     | thebetweenlands      | 3.4.11               | TheBetweenlands-3.4.11-universal.jar          | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (TickDynamic-1.12.2-1.0.3.jar)
                                        com.wildex999.patcher.TransformerPatcher
                                        com.wildex999.patcher.EntityInjector
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-44.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.11-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      LoliASM (censoredasm5.6.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
                                        shetiphian.asm.ClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      MixinBooter (!mixinbooter-7.0.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 473.81' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
  Suspected Mods: Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 473.81, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 3700X 8-Core Processor

**Comment by Rongmario** [comment]
Please re-open after trying version 8.0.
