### ISSUE TITLE
Minecraft not starting up.

### ISSUE THREAD

**Issue by vainlaind4in** [LoliKingdom/MixinBooter#28]
Minecraft 1.12.2
Forge 14.23.5.2860
MixinBooter Version 7.1

Minecraft immediately doesn't get to launch after I press the Play button on the Minecraft launcher. It doesn't load up or anything.
Here is the log: https://gist.github.com/vainlaind4in/190c8ff5b57d76bd66cc95b5940a628f

**Comment by Rongmario** [comment]
Remove MixinCompat and MixinBootstrap and also update your Java and see if it helps.

**Comment by vainlaind4in** [comment]
Removed MixinCompat and Bootstrap and it still does not work. I also doubt it's a Java problem because I have a different modpack with a similar mods list, and that somehow works. Maybe it's some sort of mixin booter incompatibility?

**Comment by Rongmario** [comment]
Noticed this mod `LootingModMC` in the logs, can you provide me with a link of where you got the mod from? It's erroring.

**Comment by KorewaLidesu** [comment]
> LootingModMC

<https://github.com/ToMe25/LootingVI/blob/1.12.2/src/main/java/com/ToMe/LootingMod/LootingMod.java#L72>

**Comment by vainlaind4in** [comment]
> Noticed this mod `LootingModMC` in the logs, can you provide me with a link of where you got the mod from? It's erroring.

I removed it and it started up normally. Thank you!

**Comment by Rongmario** [comment]
I'll note this down for future reference, seems volatile enough for it to crash with other mods also.
