### ISSUE TITLE
MixinBooter 1.12.2-8.0 Crash

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [LoliKingdom/MixinBooter#29]
When I updated MixinBooter 1.12.2 to 8.0, my game crashed when loading my mods. This didn't happen with the previous version of MixinBooter.

Here is the link to the crash report: ([https://pastebin.com/ZugVrZbk](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fZugVrZbk))

**Comment by Rongmario** [comment]
Use [Hesperus](https://www.curseforge.com/minecraft/mc-mods/hesperus), a fork of phosphor that is more updated and fixes more obscure bugs such as these.
