### ISSUE TITLE
Anti virus false positives

### ISSUE THREAD

**Issue by xJon** [LoliKingdom/MixinBooter#3]
Hi!
Recently we started using MixinBooter in Hexxit II alongside @Clienthax's patch to fix an incompatibility with Mo' Creatures.
Unfortunately since then we've gotten a few reports of people not being able to download the modpack due to Windows Defender / their anti virus programs. We can't reproduce this easily and it doesn't happen to everyone:
* ![image](https://user-images.githubusercontent.com/8945347/141651131-fe20af3d-bf8c-4b8e-a65a-d525f82804f9.png)
* https://www.virustotal.com/gui/file/fd5756dca5e74f65b85256f471d8449f8739730659037017d7290e61bfc41d7c

Do you think there's anything that can done about this?
Thanks in advance!

**Comment by clienthax** [comment]
Should just have to report it to Microsoft as false positive https://github.com/Anc813/MicMute/issues/18

**Comment by Rongmario** [comment]
Seeing as it's a `.zip`, I'm guessing you repacked it?

**Comment by xJon** [comment]
@Rongmario It is required to repack each individual mod for [Technic Solder](https://github.com/TechnicPack/TechnicSolder); inside the `.zip` it's just a `mods` folder with the `.jar` mod file inside

**Comment by Rongmario** [comment]
@xJon I see. Just ran though Virustotal and got the same result; try reporting it for being a false positive. Windows Defender for me doesn't pick anything up though, could be to do with me testing on a Win11 instance.

**Comment by xJon** [comment]
@Rongmario Reported false positive both to Windows Defender & Ikarus, you can do that too over https://github.com/hankhank10/false-positive-malware-reporting, might help.

**Comment by Rongmario** [comment]
@xJon done, it seems like mods with Mixin library are getting flagged.

**Comment by clienthax** [comment]
Not surprising given the nature of it tbh

**Comment by xJon** [comment]
![image](https://user-images.githubusercontent.com/8945347/141843286-73757e8f-db51-4607-91f3-bb408c5d439d.png)

Hopefully we'll get a response from Windows Defender soon, too.

**Comment by Rongmario** [comment]
Closing this as it is now fixed.
