### ISSUE TITLE
Latest update 8.0 crashing (Gui loop)

### ISSUE THREAD

**Issue by Desenrrollado** [LoliKingdom/MixinBooter#30]
Sorry to disturb. Uncertain on where to post this as the log indicates that Loli-Asm is causing this issue with a GUI loop. However it didn't start happening until I updated mixinbooter from 7.1 to 8.0 yesterday. 
_________________________________________________________________________________________________________________________________________
Video (Epilepsy Warning/Flashing):
https://github.com/LoliKingdom/MixinBooter/assets/92115460/47614999-fa70-4f77-9e06-32db8c27fd18

Log:
[latest.log](https://github.com/LoliKingdom/MixinBooter/files/11593455/latest.log)

Crash Report:
[crash-2023-05-29_11.41.11-client.txt](https://github.com/LoliKingdom/MixinBooter/files/11593457/crash-2023-05-29_11.41.11-client.txt)

**Comment by Rongmario** [comment]
Can you try without Roughly Enough IDs?

**Comment by Desenrrollado** [comment]
Sorry for taking so long, yes it still does the same. 
I tried additional removing some of these mods. As it began to spit a GL error after that so maybe that had to do with RenderLib, Entity Culling/Nothirium/Hesperus. However it's now back to a GUI loop. 

Removed:
![Removed mods](https://github.com/LoliKingdom/MixinBooter/assets/92115460/bed8e952-38e9-437c-a72f-8602c1fffc76)

Additionally here's the log and crash report: 

[crash-2023-05-29_20.02.07-client.txt](https://github.com/LoliKingdom/MixinBooter/files/11595043/crash-2023-05-29_20.02.07-client.txt)
[latest.log](https://github.com/LoliKingdom/MixinBooter/files/11595044/latest.log)

**Comment by Rongmario** [comment]
Wait for 8.1, debugging this should be easier.

**Comment by Rongmario** [comment]
Close for #34, please use MixinBooter 8.1 to debug.
