### ISSUE TITLE
Make a binary release

### ISSUE THREAD

**Issue by ReOne21** [LoliKingdom/MixinBooter#36]
I really don't know where I can get a game-ready build of the new version of this mod

**Comment by ReOne21** [comment]
Why can't you provide a build?

**Comment by ReOne21** [comment]
> You clone this repository and build it yourself.
Maybe I could build it, but what about others?

**Comment by KorewaLidesu** [comment]
Can you use `curse.maven` as repository?
Second, check `https://repo.cleanroommc.com/#/releases/zone/rong/mixinbooter`
