### ISSUE TITLE
8.0+ Incompatibility with DupeFix Project, causes issues with Thermal Expansion and HEI

### ISSUE THREAD

**Issue by jchung01** [LoliKingdom/MixinBooter#38]
Wasn't sure if I should post this under #34 because the crash reason is different, so just made a new issue.

As title says, MixinBooter 8 seems to be incompatible with DupeFix Project. The side effect that arises from this incompatibility is a server-side crash (caught by CensoredASM) when trying to open the GUI of any Thermal Expansion (TE) machine, leaving Thermal machines unopenable. Looking through the log, looks like HEI also fails at registering TE stuff as another side effect.

DupeFix has some mixins for Thermal Expansion, but they don't seem to be directly related to the crash. Tested with MixinBooter 8.2/8.3. MixinBooter 7.1 works fine. Here's the mod list:
![modlist](https://github.com/LoliKingdom/MixinBooter/assets/60687097/2f503635-0c4a-4c3d-9956-eac81a8d86bf)

[Crash report](https://mclo.gs/pxJBAFV)
[latest.log](https://mclo.gs/q6P62tz) (Line 304 for HEI exception, 3741 for TE)

**Comment by jchung01** [comment]
Just checked Vapaman's issue, trying to pickup an item also triggers a crash. It looks like the root cause that is shared between issues then is a `java.lang.ClassNotFoundException` for `cofh/core/gui/container/ContainerCore`, shown in [debug.log](https://mclo.gs/d6sW9qO#L602).

Now, DupeFix *does* reference `ContainerCore` in `ContainerSatchelFilterMixin`. Also, it looks like DupeFix [loads](https://github.com/focamacho/DupeFix-Project/blob/3.x/src/main/java/com/focamacho/dupefixproject/asm/DupeFixProjectCoreMod.java#L104) its mixins in [an unconventional way](https://github.com/focamacho/DupeFix-Project/blob/ba7cce628bfa509179de0c30cb42d63ca87b4efe/src/main/java/com/focamacho/dupefixproject/util/ModHandler.java#L86) by adding dependent mods as coremods to be detected? I would assume then the issue is in fact due to the way DupeFix loads mixins, so this issue probably falls under #34.

**Comment by Rongmario** [comment]
I've added it to #34.
