### ISSUE TITLE
Not compatible with Mixin 0.8.3+

### ISSUE THREAD

**Issue by LlamaLad7** [LoliKingdom/MixinBooter#4]
`MixinProcessor` [became package-private in 0.8.3](https://github.com/SpongePowered/Mixin/blob/0.8.3/src/main/java/org/spongepowered/asm/mixin/transformer/MixinProcessor.java), leading to
```
java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.LoadController
    at net.minecraftforge.fml.common.LoadController.handler$zzc000$beforeConstructing(LoadController.java:553)
```

**Comment by Rongmario** [comment]
Which mods are using Mixin 0.8.3 in 1.12.2?

**Comment by LlamaLad7** [comment]
We use Mixin 0.8.4 in <https://essential.gg/>

**Comment by LlamaLad7** [comment]
You could probably just reflect to get the class instead like with some of the other ones in that mixin.

**Comment by Rongmario** [comment]
Yeah, was just wondering who was using it. Wasn't aware of that project, thanks!

**Comment by LlamaLad7** [comment]
Thanks!

**Comment by Rongmario** [comment]
3.1 will be out soon, please check if essentials is compatible with it.
