### ISSUE TITLE
Does exist a complete documentation ?

### ISSUE THREAD

**Issue by quentin452** [LoliKingdom/MixinBooter#45]
Because the [README.md](https://github.com/LoliKingdom/MixinBooter#readme) seem to incomplete

**Comment by quentin452** [comment]
OK lill try later

**Comment by KorewaLidesu** [comment]
Oh I forgot about something, put the mixin config in resource folder
Put config name and return it in `getMixinConfigs` (return as ImmutableList if you only have 1 mixin config, else just load what you need in the list)

**Comment by quentin452** [comment]
Like I don't know where I need to add IEarlyMixinLoader by example

**Comment by quentin452** [comment]
Ah OK I found it it's in the mixinbooter source code

**Comment by Rongmario** [comment]
Always consult the library's comments first, I will expand on the README when I have some time though, thank you!
