### ISSUE TITLE
 Crash after updating mixinbooter 3.0->3.2

### ISSUE THREAD

**Issue by SpeeeDCraft** [LoliKingdom/MixinBooter#9]
I used to have mixinbooter 3.0 and mixincompat 0.7-0.8 installed. As I read in changelog, the second one is no longer needed. I deleted it and updated mixinbooter to 3.2, but I get the same error.

[crash-2022-01-21_09.49.50-client.txt](https://github.com/LoliKingdom/MixinBooter/files/7910253/crash-2022-01-21_09.49.50-client.txt)

**Comment by magcicada** [comment]
It also Incompatible with MixinBootstrap ,you need delete this mod.

**Comment by Rongmario** [comment]
What about https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/3614763?

**Comment by magcicada** [comment]
it works for me.

**Comment by SpeeeDCraft** [comment]
> What about https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/3614763?

I deleted **MixinBootstrap** as they said above, and installed the **thin** version and everything worked

**Comment by Rongmario** [comment]
I'll try fix this the proper way by dealing with other mods.

**Comment by Macleykun** [comment]
Something I want to add
If the newest update is downloaded trough the curse client it’ll append the . Infront of the file name.

when it’s downloaded directly from the website it actually won’t have a . Infront of it.

I suggest to maybe. Use a different letter like ! Perhaps?
.filename.ext is also used to make files hidden in Linux.
